"""empty message

Revision ID: 339e31f80c56
Revises: ffdc0a98111c
Create Date: 2023-01-24 13:17:42.589044

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '339e31f80c56'
down_revision = 'ffdc0a98111c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('first_name', sa.String(length=1000), nullable=False))
    op.add_column('users', sa.Column('last_name', sa.String(length=1000), nullable=False))
    op.add_column('users', sa.Column('profile_pic', sa.String(length=1000), nullable=True))
    op.add_column('users', sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'updated_at')
    op.drop_column('users', 'profile_pic')
    op.drop_column('users', 'last_name')
    op.drop_column('users', 'first_name')
    # ### end Alembic commands ###