"""empty message

Revision ID: 2cf95946ee05
Revises: 80302b9c8665
Create Date: 2023-01-26 00:28:18.612004

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '2cf95946ee05'
down_revision = '80302b9c8665'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('birthday', sa.String(length=255), nullable=False))
    op.add_column('users', sa.Column('gender', sa.String(length=255), nullable=False))
    op.alter_column('users', 'profile_pic',
               existing_type=sa.VARCHAR(length=1000),
               nullable=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('users', 'profile_pic',
               existing_type=sa.VARCHAR(length=1000),
               nullable=True)
    op.drop_column('users', 'gender')
    op.drop_column('users', 'birthday')
    # ### end Alembic commands ###