"""empty message

Revision ID: 235e827653bb
Revises: cd3202e05def
Create Date: 2024-01-04 08:23:33.431135

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '235e827653bb'
down_revision = 'cd3202e05def'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('post_likes', sa.Column('id', sa.Integer(), nullable=False))
    op.drop_column('post_likes', 'created_at')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('post_likes', sa.Column('created_at', sa.DATETIME(), nullable=True))
    op.drop_column('post_likes', 'id')
    # ### end Alembic commands ###
