"""empty message

Revision ID: f2e63cfc8138
Revises: 235e827653bb
Create Date: 2024-01-18 09:16:00.019568

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f2e63cfc8138'
down_revision = '235e827653bb'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('post_likes', 'created_at')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('post_likes', sa.Column('created_at', sa.DATETIME(), nullable=True))
    # ### end Alembic commands ###
